#!/bin/bash

read name
echo "hello $name"

#実行コマンド
# hashiguchi.haruto-01@mbp shell % ./hello
# hashiguchi　ユーザーに入力させる
# hello hashiguchi


read -p "Name: " name # -pはプロンプトの意
echo "hello $name"

# 実行コマンド
# hashiguchi.haruto-01@mbp shell % ./hello
# Name: hashiguchi　ユーザーに入力させる
# hello hashiguchi


read -p "Pick 3 colors: " c1 c2 c3
echo $c1
echo $c2
echo $c3

# 実行コマンド
# hashiguchi.haruto-01@mbp shell % ./hello
# Pick 3 colors: red blue green　ユーザーに入力させる
# red
# blue
# green

# 実行コマンド
# hashiguchi.haruto-01@mbp shell % ./hello
# Pick 3 colors: red blue 　一つ足りない場合
# red
# blue

# hashiguchi.haruto-01@mbp shell % 

# 実行コマンド
# hashiguchi.haruto-01@mbp shell % ./hello
# Pick 3 colors: red blue　green pink 　一つ多い場合
# red
# blue
# green pink 最後にふたつ並ぶ
# hashiguchi.haruto-01@mbp shell % 
