#!/bin/bash

# 1~5を順番に出力したい場合
for i in 1 2 3 4 5
do
  echo $i
done

# 条件の部分で配列を使用できる
a=(1 2 3 4 5)

for i in ${a[@]} # 配列を全て展開
do
  echo $i
done

# 条件を書かない方法は、seqを使う
for i in `seq 1 100`
do
  echo $i
done
# 1~100まで出力される

for i in `seq 1 5 100`
do
  echo $i
done
# 1~100までを、第二引数の値ずつ出力

for i in `seq 3 5`
do
  echo $i
done
# 引数が二つの場合、第一引数から第二引数まで1 or -1ずつ出力
