#!/bin/bash

# echo 5+2

# echo `expr 5 + 2`

echo $((5 + 2))

# 実行コマンド
# hashiguchi.haruto-01@mbp shell % ./hello
# 7

n=5
#(($n=$n+5))
((n=n+5))
echo $n

# hashiguchi.haruto-01@mbp shell % ./hello
# 10

# + - * / % ** ++ --

echo $((10 / 3)) # 3 ->bashでは整数の演算しかできないため、小数点は省かれる

